### Crear cuenta
POST localhost:8080/create
Content-Type: application/json

{
  "nombre": "Juan Sebastian Gonzalez Lopez",
  "balance": 1000
}

### Depositar fondos
POST localhost:8080/deposit
Content-Type: application/json

{
  "clientId": "594d13d1-1d74-4866-a605-0f93bbc63ea3",
  "amount": 150
}

### Eliminar cuenta
POST localhost:8080/delete/594d13d1-1d74-4866-a605-0f93bbc63ea3


### Retirar fondos
POST localhost:8080/withdraw
Content-Type: application/json

{
  "clientId": "594d13d1-1d74-4866-a605-0f93bbc63ea3",
  "amount": 20
}

### Obtener csv cuentas mysql
GET localhost:8080/accounts-mysql


### Obtener csv transacciones mysql
GET localhost:8080/transactions-mysql


### login
GET http://localhost:8080/login/4793c3e8-2370-4301-a368-d72f08fab065
