### Crear cuenta
POST localhost:8080/create
Content-Type: application/json

{
  "nombre": "Victor Sanchez Grande",
  "balance": 200
}

### Depositar fondos
POST localhost:8080/deposit
Content-Type: application/json

{
  "clientId": "808c713f-36f5-4799-88ea-20487f29142a",
  "amount": 60,
  "dbType": "MYSQL"
}

### Eliminar cuenta
POST localhost:8080/delete/ab29a574-1e49-475c-930e-dcb28c51ef0b


### Retirar fondos
POST localhost:8080/withdraw
Content-Type: application/json

{
  "clientId": "808c713f-36f5-4799-88ea-20487f29142a",
  "amount": 10,
  "dbType": "MYSQL"
}